package com.polime.enums;

public enum EResponseCode {
    SUCCESS, NOT_FOUND, INTERNAL_ERROR, METHOD_NOT_ALLOWED, VALIDATION_ERROR, DUPLICATE_RESOURCE, RESOURCE_NOT_FOUND,
    INVALID_CREDENTIALS, UNAUTHORIZED, INVALID_JSON_SYNTAX, DATABASE_ERROR
}
